### ISSUE TITLE
The Ugly Side of React Hooks

### ISSUE THREAD

**Issue by highestop** [highestop/feer-readings#32]
https://medium.com/swlh/the-ugly-side-of-hooks-584f0f8136b6

翻译：https://mp.weixin.qq.com/s/oFdOStxPdxdgw4E-kgdc2g

**Comment by lsdsjy** [comment]
看完之后感觉如鲠在喉，对应原文顺序一条条来吐槽：

### Motivation #1: Classes are confusing
这一部分原作者说的还算中肯，hooks API 确实增加了心智负担。
但是关于
> Personally, I liked the idea that when I stumbled upon a function component, I could immediately know that this is a “dumb component” without a state. Sadly, with the introduction of Funclasses, this is not the situation anymore.

这一段，无法理解这种 `immediately know` 有何意义。如果一个组件是第三方库引入的，开发者会关心它是否 stateful 吗？组件作为基本的抽象单位，对使用方应该是黑盒的状态。即使是自己项目里写出的组件，也不需要开发者时刻关心它的实现细节。

### Motivation #2: It’s hard to reuse stateful logic between components
这是 React Hooks 以及 Vue Composition API 最大的优点，作为逻辑复用的单元，比 Mixin、HOC 等 API 更安全、易用。作者提的很可笑的一点是认为 React Hooks 没有提供状态管理解决方案，然而这从来都不是 Hooks / VCA 要解决的问题。只能说作者弄混了这个 Motivation 的真正含义，或者说含糊了 `stateful logic` 和 `state` 的区别，把 `sharing state` 和 `reusing logic` 混为一谈。

### Motivation #3: Complex components become hard to understand
作者认为把组件内多个不相关逻辑放在各个生命周期内没啥问题，而且还可以通过抽成外部函数的方式减少组件内部代码量。关于这一点：
1. Hooks 关心的不是代码的体积而是位置，同一业务功能的代码应该放在一起，这里可以借用 VCA 的那张经典对比图：
[VCA Comparison](https://user-images.githubusercontent.com/499550/62783026-810e6180-ba89-11e9-8774-e7771c8095d6.png)
2. 不同生命周期里的不同业务逻辑逐个抽成外部函数，本质上相当于 Mixin，而 Mixin 的缺点已经是老生常谈的话题了。

> with the class component, you can tell at first glance what the component is doing on mount

从这一句可以看出作者被生命周期这一套术语荼毒不浅。Hooks 这种范式强调业务逻辑本身，关注组件的生命周期是没有意义的，或者说应该从更高的角度来看待组件的职责，而非底层的“挂载时应该做什么，更新时应该做什么”。这就像第一次接触纯函数式编程语言的人一定会奇怪：“如果我连变量赋值都用不了要怎么写程序”？事实上完全没有问题，甚至可以写得更好。
> It’s only after I stopped looking at the useEffect Hook through the prism of the familiar class lifecycle methods that everything came together for me. - Dan Abramov, React Core Team

### Motivation #4: Performance
这里作者貌似刻意忽略了原文提到的 Function 相比 Class 在 Hot Reloading、Code Minifying 方面的优势，把 Performance 的范围局限在了运行时性能。另外作者一直叫嚣没有 “numbers” 证明 Hooks 的性能优势，我特意上 https://github.com/krausest/js-framework-benchmark 查了一下，对比 `react-17` 和 `react-hooks-17` 两者，虽然差距并不明显，但 Hooks 在性能上确实有所提升。

### Motivation #5: Funclasses are less verbose
关于 `useMemo` 之类的点，没有异议，确实增加了心智负担，且代码变得 "more verbose"。但是关于`useContext`这一点，作者想要的这种写法目前在 React 体系里是做不到的，`Context.Consumer` 和 `useContext` 这些 API 之所以存在，是因为 React 不会对 JSX 进行静态分析（基于心智模型和可行性考虑也不打算做静态分析），所以用户必须显式地指明当前组件依赖哪个 Context。不想手动指定也可以，用 Vue 就行了（

### The hidden side effect
前面说了，组件应当视作黑盒。另外，自定义 Hooks 作为逻辑抽象的手段，抽象之前应该在组件内写完、测试。如果一开始就按照自定义 Hooks 的方式写组件，必然会增加调试成本，所谓过早优化是万恶之源，无论是优化性能还是优化代码结构，都是如此。

### Bloated API
作者认为 Hooks 的缺点这么多，那么这一点就没什么可争论。然而对于能 get 到 Hooks 的优点的开发者而言，API 的增加和理解成本相比它带来的收益实在是太低了。

### Lack of declarativity
关于找 return，一方面可以借助 IDE 的能力，另一方面当组件体积大到没法快速找到 JSX 部分时，就应该考虑拆分组件、抽象逻辑了。

### Coupling everything to React
对第三方库作者而言依然可以用 vanilla JS 写普适的库，针对 React 做一层包装即可；使用者也可以自己选择 raw or wrapped API。

总之通篇看下来觉得作者要么不懂 Hooks，要么为了哗众取宠，也可能兼而有之。

**Comment by lsdsjy** [comment]
顺便贴一下 https://vue-composition-api-rfc.netlify.app/#comparison-with-react-hooks，这是我看过的对 React Hooks 最精准的吐槽之一

**Comment by PeterChen1997** [comment]
> 看完之后感觉如鲠在喉，对应原文顺序一条条来吐槽：
> 
> ### Motivation #1: Classes are confusing
> 这一部分原作者说的还算中肯，hooks API 确实增加了心智负担。
> 但是关于
> 
> > Personally, I liked the idea that when I stumbled upon a function component, I could immediately know that this is a “dumb component” without a state. Sadly, with the introduction of Funclasses, this is not the situation anymore.
> 
> 这一段，无法理解这种 `immediately know` 有何意义。如果一个组件是第三方库引入的，开发者会关心它是否 stateful 吗？组件作为基本的抽象单位，对使用方应该是黑盒的状态。即使是自己项目里写出的组件，也不需要开发者时刻关心它的实现细节。
> 
> ### Motivation #2: It’s hard to reuse stateful logic between components
> 这是 React Hooks 以及 Vue Composition API 最大的优点，作为逻辑复用的单元，比 Mixin、HOC 等 API 更安全、易用。作者提的很可笑的一点是认为 React Hooks 没有提供状态管理解决方案，然而这从来都不是 Hooks / VCA 要解决的问题。只能说作者弄混了这个 Motivation 的真正含义，或者说含糊了 `stateful logic` 和 `state` 的区别，把 `sharing state` 和 `reusing logic` 混为一谈。
> 
> ### Motivation #3: Complex components become hard to understand
> 作者认为把组件内多个不相关逻辑放在各个生命周期内没啥问题，而且还可以通过抽成外部函数的方式减少组件内部代码量。关于这一点：
> 
> 1. Hooks 关心的不是代码的体积而是位置，同一业务功能的代码应该放在一起，这里可以借用 VCA 的那张经典对比图：
>    [VCA Comparison](https://user-images.githubusercontent.com/499550/62783026-810e6180-ba89-11e9-8774-e7771c8095d6.png)
> 2. 不同生命周期里的不同业务逻辑逐个抽成外部函数，本质上相当于 Mixin，而 Mixin 的缺点已经是老生常谈的话题了。
> 
> > with the class component, you can tell at first glance what the component is doing on mount
> 
> 从这一句可以看出作者被生命周期这一套术语荼毒不浅。Hooks 这种范式强调业务逻辑本身，关注组件的生命周期是没有意义的，或者说应该从更高的角度来看待组件的职责，而非底层的“挂载时应该做什么，更新时应该做什么”。这就像第一次接触纯函数式编程语言的人一定会奇怪：“如果我连变量赋值都用不了要怎么写程序”？事实上完全没有问题，甚至可以写得更好。
> 
> > It’s only after I stopped looking at the useEffect Hook through the prism of the familiar class lifecycle methods that everything came together for me. - Dan Abramov, React Core Team
> 
> ### Motivation #4: Performance
> 这里作者貌似刻意忽略了原文提到的 Function 相比 Class 在 Hot Reloading、Code Minifying 方面的优势，把 Performance 的范围局限在了运行时性能。另外作者一直叫嚣没有 “numbers” 证明 Hooks 的性能优势，我特意上 https://github.com/krausest/js-framework-benchmark 查了一下，对比 `react-17` 和 `react-hooks-17` 两者，虽然差距并不明显，但 Hooks 在性能上确实有所提升。
> 
> ### Motivation #5: Funclasses are less verbose
> 关于 `useMemo` 之类的点，没有异议，确实增加了心智负担，且代码变得 "more verbose"。但是关于`useContext`这一点，作者想要的这种写法目前在 React 体系里是做不到的，`Context.Consumer` 和 `useContext` 这些 API 之所以存在，是因为 React 不会对 JSX 进行静态分析（基于心智模型和可行性考虑也不打算做静态分析），所以用户必须显式地指明当前组件依赖哪个 Context。不想手动指定也可以，用 Vue 就行了（
> 
> ### The hidden side effect
> 前面说了，组件应当视作黑盒。另外，自定义 Hooks 作为逻辑抽象的手段，抽象之前应该在组件内写完、测试。如果一开始就按照自定义 Hooks 的方式写组件，必然会增加调试成本，所谓过早优化是万恶之源，无论是优化性能还是优化代码结构，都是如此。
> 
> ### Bloated API
> 作者认为 Hooks 的缺点这么多，那么这一点就没什么可争论。然而对于能 get 到 Hooks 的优点的开发者而言，API 的增加和理解成本相比它带来的收益实在是太低了。
> 
> ### Lack of declarativity
> 关于找 return，一方面可以借助 IDE 的能力，另一方面当组件体积大到没法快速找到 JSX 部分时，就应该考虑拆分组件、抽象逻辑了。
> 
> ### Coupling everything to React
> 对第三方库作者而言依然可以用 vanilla JS 写普适的库，针对 React 做一层包装即可；使用者也可以自己选择 raw or wrapped API。
> 
> 总之通篇看下来觉得作者要么不懂 Hooks，要么为了哗众取宠，也可能兼而有之。

hidden side effect 这里说的问题我感觉还是存在的，有点类似 rxjs 里流不好追溯一样，就算是将十分成熟的逻辑抽离成 hooks，也不可避免的在后面的维护中被多次查看，因为需求肯定是会变得（懂得都懂
