### ISSUE TITLE
抛弃 Sass / Less ，迎接原子化 CSS 时代

### ISSUE THREAD

**Issue by highestop** [highestop/feer-readings#37]
https://mp.weixin.qq.com/s/xSxAr0irZOGCE88ZTPjSZw

**Comment by yanhaijing** [comment]
抛弃 Sass / Less ，迎接原生 CSS 不好么o(╯□╰)o

**Comment by highestop** [comment]
> 抛弃 Sass / Less ，迎接原生 CSS 不好么o(╯□╰)o

哈哈，其实我觉得原生挺好的，CSS-in-JS 或者 CSS Variable 就挺好的

**Comment by PeterChen1997** [comment]
taliwind 这类原子 CSS 库，感觉可以在降低 CSS 编写成本的同时，一定程度的统一团队内 CSS 规范
并且如果团队成员对于类的含义了熟于心，其实还能降低一些 CSS 类声明的理解成本

**Comment by highestop** [comment]
> 抛弃 Sass / Less ，迎接原生 CSS 不好么o(╯□╰)o
> 
> Sass / Less 写业务 就一个嵌套，变量？ 原生css都支持了（不支持还可以用postcss）

之前有同事问过 AntD 团队是否要全面支持 CSS-Variable，然后好像说改不动..

现在有些时候为了保证 AntD 主题功能效果一致还是得用 Less，但是自己写很多都是纯 CSS 了
